spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer?useSSL=true
    username: root
    password: alekhya
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update